services:
  - type: web
    name: law-app
    runtime: static
    plan: free
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: dist
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: "true"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
